function headerUI(){
	return '<div id="hb">'
+'<section id="banner">'
+'<div class="bg-color">'
+'  <header id="header">'
+'    <div class="container">'
+'      <div id="mySidenav" class="sidenav">'
+'        <a href="javascript:void(0)" class="closebtn" onclick="closeNav()"> &times; </a>'
+'        <a id="login_btn">Login</a>'
+'        <a id="add_btn">Join</a>'
+'        <a id="board_btn">Board</a>'
+'      </div>'
+'      <span onclick="openNav()" class="pull-right menu-icon">☰</span>'
+'    </div>'
+'  </header>'
+'  <div class="container">'
+'    <div class="row">'
+'      <div class="inner text-center">'
+'        <h1 class="logo-name"> Grade Management System </h1>'
+'        <h2>TAETAE</h2>'
+'        <p>-v-</p>'
+'      </div>'
+'    </div>'
+'  </div>'
+'</div>'
+'</section>'
+'</div>';
}

