function readerUI(){
	return '<section class="content">'
	+'<div class="row">'
	+'<div class="col-md-12">'
		+'<div class="box box-primary">'
			+'<div class="box-body">'
				+'<div class="form-group">'
					+'<label for="exampleInputEmail1">Title</label>'
					+'<p id="title" class="form-control"></p>'
				+'</div>'
				+'<div class="form-group">'
					+'<label for="exampleInputPassword1">Content</label>'
					+'<textarea class="form-control" id="cnt" rows="3" readonly="readonly"></textarea>'
				+'</div>'
				+'<div class="form-group">'
					+'<label for="exampleInputEmail1">Writer</label>'
					+'<p id="writer" class="form-control"><p/>'
				+'</div>'
			+'</div>'
		+'</div>'
	+'</div>'
	+'</div>'
	+'</section>';
}
