function writerUI(){
	return '<section class="content">'
	+'<div class="row">'
	+'<div class="col-md-12">'
		+'<div class="box box-primary">'
+'<div class="box-body">'
	+'<div class="form-group">'
		+'<label for="exampleInputEmail1">Title</label> '
		+'<input type="text" id="title" class="form-control" placeholder="Enter Title">'
	+'</div>'
	+'<div class="form-group">'
		+'<label for="exampleInputPassword1">Content</label>'
		+'<textarea class="form-control" id="ctn" rows="3"'
			+'placeholder="Enter ..."></textarea>'
	+'</div>'
	+'<div class="form-group">'
		+'<label for="exampleInputEmail1">Writer</label> '
		+'<input type="text"'
			+'id="writer" class="form-control" placeholder="Enter Writer">'
	+'</div>'
+'</div>'
		+'</div>'
	+'</div>'
+'</div>'
+'</section>'
+'</div>';
}
