CREATE TABLE POINT(
    POINT_SEQ INT PRIMARY KEY AUTO_INCREMENT,
    ALL_POINT INT DEFAULT 10000,
    MBR_POINT INT DEFAULT 0,
    MEMBER_ID VARCHAR(20)
);

DROP TABLE POINT;

SELECT * FROM POINT;

SELECT MEMBER_ID FROM MEMBER;
INSERT INTO POINT(MEMBER_ID)VALUES('DA26');
INSERT INTO POINT(MEMBER_ID)VALUES('HJ34');
INSERT INTO POINT(MEMBER_ID)VALUES('HR26');
INSERT INTO POINT(MEMBER_ID)VALUES('HT21');
INSERT INTO POINT(MEMBER_ID)VALUES('J27');
INSERT INTO POINT(MEMBER_ID)VALUES('JE26');
INSERT INTO POINT(MEMBER_ID)VALUES('JH23');
INSERT INTO POINT(MEMBER_ID)VALUES('JH32');
INSERT INTO POINT(MEMBER_ID)VALUES('JK30');
INSERT INTO POINT(MEMBER_ID)VALUES('JT26');
INSERT INTO POINT(MEMBER_ID)VALUES('KE29');
INSERT INTO POINT(MEMBER_ID)VALUES('NR30');
INSERT INTO POINT(MEMBER_ID)VALUES('SH29');
INSERT INTO POINT(MEMBER_ID)VALUES('ST30');
INSERT INTO POINT(MEMBER_ID)VALUES('TH25');
INSERT INTO POINT(MEMBER_ID)VALUES('YH31');
INSERT INTO POINT(MEMBER_ID)VALUES('SJ26');

INSERT INTO POINT(MEMBER_ID)VALUES('S29');
INSERT INTO POINT(MEMBER_ID)VALUES('SI35');